version: '3.8'

name: smm-service
services:
  traefik:
    image: traefik:v3
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    image: zethange/cmm-backend:latest
    depends_on: 
      - postgres
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`prodanocontest.ru`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smm_service_db
      - POSTGRES_HOST=postgres

  frontend:
    image: zethange/cmm-frontend:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`prodanocontest.ru`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  postgres:
    image: postgres:16.2
    restart: always
    ports:
      - "5438:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smm_service_db

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5681:5672"
      - "15681:15672"
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=smm_service
      - RABBITMQ_DEFAULT_PASS=smm_service_pass
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: always

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9011:9000"
      - "9012:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: smm_service
      MINIO_ROOT_PASSWORD: smm_service_pass
      MINIO_ACCESS_KEY: smm_service_key
      MINIO_SECRET_KEY: smm_service_secret_key
    restart: always

  create_minio_buckets:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c '
      mc config host add s3 http://minio:9000 smm_service smm_service_pass --api S3v4;
      [[ ! -z "`mc ls s3 | grep smm_service`" ]] || mc mb s3/smm-service;
      exit 0;
      '

volumes:
  postgres-data:
  rabbitmq-data:
  minio-data:
